version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apichat.rule=Host(`apichat.crisego.com`)"
      - "traefik.http.routers.apichat.entrypoints=websecure"
      - "traefik.http.routers.apichat.tls=true"
      - "traefik.http.services.apichat.loadbalancer.server.port=3000"
    environment:
      # PORT must be exposed by 80
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - PORT=${PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - FRONT_END_HOST=${FRONT_END_HOST}
    # ports:
    #   - "${APP_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - traefik-docker-compose_default
networks:
  traefik-docker-compose_default:
    external: true
